version: '3'

services:
  database:
    env_file:
      - .env
    container_name: mysql_db
    image: mysql/mysql-server:8.0-aarch64
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_HOST: ${HOST}
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      TZ: 'Asia/Seoul'

    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  application:
    env_file:
      - .env
    container_name: spring-project
    restart: on-failure
    image: jacobhboy/sickgyun-server:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - test_network