server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USER}
    password: ${PASSWORD}

  logging:
    level:
      org:
        hibernate:
          SQL: debug

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

decorator:
  datasource:
    p6spy:
      enable-logging: true

---
#S3
aws:
  s3:
    bucket: ${S3_BUCKET}
    access-key: ${S3_ACCESSKEY}
    secret-key: ${S3_SECRET}

---
#JWT
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-time: ${ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}

---
#recruit
recruit:
  url: ${RECRUIT_URL}

---
#event
event:
  url: ${EVENT_URL}