server:
  port: 8081
  servlet:
    contextPath: /api
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${MONGO_DB}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"