name: cd
on:
  workflow_run:
    workflows: [ "ci" ]
    paths:
      - 'main-server/**'
      - 'logging-server/**'
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            main:
              - 'main-server/**'
            logging:
              - 'logging-server/**'

      - name: deploy main-server
        if: steps.changes.outputs.main == 'true'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            chmod +x ~/script/deploy-main-server.sh
            zsh ~/script/deploy-main-server.sh

      - name: deploy logging-server
        if: steps.changes.outputs.logging == 'true'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            chmod +x ~/script/deploy-logging-server.sh
            zsh ~/script/deploy-logging-server.sh

